### ISSUE TITLE
pixman 0.34.0 tests fail entire build on High Sierra

### ISSUE THREAD

**Issue by jhaungs** [OpenSmalltalk/opensmalltalk-vm#258]
A plain ./mvm build on MacOS 10.13.4 (in any of the build.macos64x64/pharo.* directories) fails with this error:

> utils-prng.c:207:27: error: use of unknown builtin '__builtin_shuffle' [-Wimplicit-function-declaration]
>             randdata.vb = __builtin_shuffle (randdata.vb, bswap_shufflemask);
>                           ^
> utils-prng.c:207:25: error: assigning to 'uint8x16' (vector of 16 'uint8_t' values) from incompatible type 'int'
>             randdata.vb = __builtin_shuffle (randdata.vb, bswap_shufflemask);
>                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 

It's trying to build the tests for pixman. There is a patch for this bug here: https://bugs.freedesktop.org/show_bug.cgi?id=104886

But when I apply the patch, the patched utils-prng.c file gets overwritten with the old version by something in the build or configure step, so the patch disappears and the build error recurs.

**Comment by PierceNg** [comment]
> But when I apply the patch, the patched utils-prng.c file gets overwritten with the old version by something in the build or configure step, so the patch disappears and the build error recurs.

The original tarball is cached in opensmalltalk-vm/.thirdparty-cache, and the build process untars, reconfigures and builds afresh each time. To fix, apply the patch to the cached tarball.

**Comment by nicolas-cellier-aka-nice** [comment]
This issue seems obsolete, the builds work nowadays => I close
