### PR TITLE
Customization for Pharo & About Dialog 

### PR DESCRIPTION
**Pull request by demarey**
should close PR #388

### CODE REVIEW

**Review by eliotmiranda — APPROVED** [review]

**Comment by eliotmiranda** [comment]
Hi Christophe,

    when I try and build a PharoVM from the Cog sources after merging this pull request I get the following error:

```../../platforms/iOS/vm/OSX/SqueakOSXApplication.m:76:37: error: no visible @interface for 'sqSqueakMainApplication' declares the selector 'setAboutWindow:'
    [gDelegateApp.squeakApplication setAboutWindow: [self keyWindow]];
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~
1 error generated.```

It's coming from this method:

```@implementation SqueakOSXApplication
...
- (void)orderFrontStandardAboutPanel:(id)sender;
{
    [super orderFrontStandardAboutPanel: sender];
    [gDelegateApp.squeakApplication setAboutWindow: [self keyWindow]];
}```
